### ISSUE TITLE
TritonCTS does not find lemon on Ubuntu 21.04

### ISSUE THREAD

**Issue by Unkraut3** [The-OpenROAD-Project/OpenROAD#1186]
When running `./build_openroad.sh --local` on ubuntu 21.04 the cmake script for TritonCTS does not find lemon even though lemon-dev was installed via apt.

The reason is, that the cmake scripts are searching for LEMONConfig.cmake or lemon-config.config. However, on Ubuntu 21.04 the cmake file is called lemonConfig.cmake. The cmake scripts should therefoe also search for lemonConfig.cmake.

**Comment by maliberty** [comment]
I don't know who packaged this for Ubuntu but in the source library you'll see

LEMONConfig.cmake.in
[https://lemon.cs.elte.hu/trac/lemon/browser/lemon/cmake]

So LEMONConfig.cmake is the expected name and not lemonConfig.cmake.  This seems more like an Ubuntu issue; I don't see anything to fix in OR.

**Comment by shenki** [comment]
Someone reported this bug:

 https://bugs.launchpad.net/ubuntu/+source/liblemon/+bug/1827886
  https://lemon.cs.elte.hu/trac/lemon/ticket/628
  
And send this commit to the Debian packging:
  
  https://salsa.debian.org/med-team/liblemon/-/merge_requests/2
  
Which was merged. This fixed the package for the person who opened the bug, but broke lemon's cmake detection for everyone else.
  
Given upstream lemon still uses `LEMONConfig.cmake`, we should get Debian to undo this change.

In order to support existing releases of Debian and Ubuntu, according to https://cmake.org/cmake/help/latest/command/find_package.html#full-signature we can change the detection to do this:
```
find_package(LEMON NAMES LEMON lemon REQUIRED)
```
