### ISSUE TITLE
[INFO DRT-1000] Pin u_sram_2kb/din0[15] not in any guide. Attempting to patch guides to cover (at least part of) the pin.

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenROAD#1197]
Is this information is saying any specific issue here ?  I see u_sram_2kb/din0[15]  connected to mem_din_b\[15\] and this signal information is available inside guide file : 16-fastroute.guide

openroad version: OpenROAD v2.0-1285-g92dd19146 

Attached the setup
[exp3.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/7336972/exp3.tar.gz)

Run command: run_cmd

In the MPW-3 Efabless openroad version: OpenROAD 1 fb8ae93b6c7a5eb0e6fac83360a8a48d76c41885
This  reported as ERROR below:
<pre>[WARNING DRT-0215] Pin u_sram_2kb/din0[15] not covered by guide.
[WARNING DRT-0215] Pin u_sram_2kb/din0[15] not covered by guide.
[WARNING DRT-0225] mem_din_b\[15\] 2 pin not visited, fall back to feedthrough mode.
[WARNING DRT-0224] mem_din_b\[15\] 2 pin not visited, number of guides = 7.
[ERROR DRT-0218] Guide is not connected to design.
Error: or_droute.tcl, 34 DRT-0218
<font color="#CC0000">[ERROR]: during executing: &quot;openroad -exit /openLANE_flow/scripts/openroad/or_droute.tcl |&amp; tee &gt;&amp;@stdout /project/openlane/user_project_wrapper/runs/13-10_09-31/logs/routing/18-tritonRoute.log&quot;</font>
</pre>

**Comment by eder-matheus** [comment]
@dineshannayya I've run the attached testcase on a CentOS 7 machine and I see the `[INFO DRT-1000] Pin u_sram_2kb/din0[15] not in any guide. Attempting to patch guides to cover (at least part of) the pin.` message, but it is not failing with the latest OpenROAD. Could you try it with the latest version of OpenROAD?

**Comment by dralabeing** [comment]
This sounds like an Openlane bug as well  based on the initial version reported on MPW-3.
@maliberty @eder-matheus Should this also be submitted against OpenLane to fix against that OR version too since that is the latest shuttle version?

**Comment by eder-matheus** [comment]
> @eder-matheus yes, in the latest version OPENROAD I see this as only [INFO] .. Question is what is the impact of this info ? Design wise I don't see any special on u_sram_2kb/din0[15] over rest of the u_sram_2kb/din0 32 bits ? Why tool showing info only on [15] bit ?
> 
> I have used same SRAM memory in one more OPLANE project and even in older version of OPENROAD, I don't find issue their?

@dineshannayya I'm not sure about what this message from the detailed router means, but my guess is the route guide is partially covering this pin of the macro and the detailed router only completes the coverage of the pin. Also, since the routing ends with no DRCs, I think this message doesn't have a great impact on the final result. @maliberty does it make sense?

**Comment by eder-matheus** [comment]
@maliberty I've revisited this issue and found out why we have the DRT warnings for the route guides. The pin that has the warning is not aligned with a routing track, as shown in the figure below:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/43450810/206696238-21b80538-bdf4-4b5b-8f75-eca4d8bb8ae3.png">

In such cases, GRT looks for the nearest track and uses the track coordinate (in this case, the X coordinate) to assign the pin to a position in the global routing grid. This track is on the grid position adjacent to the pin grid position. The figure below shows that the guide boundary is aligned with the track:
<img width="706" alt="image" src="https://user-images.githubusercontent.com/43450810/206696675-76c1af9e-b7b0-44ea-a003-98b1e418e805.png">

Running pin_access before GRT solves the warning because GRT will use the AP of the pin to compute the on-grid position.

**Comment by maliberty** [comment]
Couldn't you have the same issue with pin_access?  It seems it is more about snapping than aps.

**Comment by maliberty** [comment]
Perhaps we should not snap in the non-pa case if doing so would move the point onto the edge of the shape.
