### ISSUE TITLE
USEMINSPACING OBS OFF breaks sky130 hd chameleon_hier

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#1550]
re: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/commit/9da2d0659588f37dfea7771b7de6d623b486b050

@antonblanchard this has broken the ORFS test sky130 hd chameleon_hier.  Do you have time to look into it?  The router fails with 

[ERROR DRT-0073] No ap for ibex_core/HADDR[10].

I guess the "USEMINSPACING OBS OFF" makes the pin inaccessible.

**Comment by maliberty** [comment]
@vvbandeira FYI

**Comment by antonblanchard** [comment]
I can have a go. sky130hd chameleon_hier dies in detailed placement with my setup, so I need to sort that out first:
```
[ERROR DPL-0018] detailed placement failed on RAM.genblk1\[0\].RAM.
```

**Comment by antonblanchard** [comment]
@maliberty the issue is we only have minimum clearance around the pins:
![bad_pin](https://user-images.githubusercontent.com/2029971/149495132-59293607-a9aa-4d51-a16b-f88ed011b191.png)

Creating a wide spacing clearance fixes it:

![good_pin](https://user-images.githubusercontent.com/2029971/149495223-a1499edc-f5d8-4215-8b7c-c475aec3d8e4.png)

Which I guess is expected since the blockage around it is very wide. It does mean that pretty much every pin needs wide spacing clearance.

One option is to back this patch out of ORFS, and continue to work on the `write_abstract_lef` patch.

**Comment by maliberty** [comment]
I think backing it out is best (would you make a PR to do so?).  I pointed out the same issue was likely with your other PR due to the min spacing assumption.

**Comment by vijayank88** [comment]
With latest commit not facing any issue with chameleon_hier and flow completes successfully.
