### ISSUE TITLE
Allow selection of dbITerm in the GUI

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenROAD#3409]
### Description

If you click on an iterm the instance is selected today.  It would be good if you could directly select the iterm.

### Suggested Solution

The existing instance selection rtree can be kept but then a secondary search inside the master to see if an mterm is selected should be made.  If one is found then the corresponding iterm can be found.

**Comment by Iyury1** [comment]
I can also work on another issue if someone else was planning to do this one.

**Comment by maliberty** [comment]
It's yours.  Thanks

**Comment by Iyury1** [comment]
I am almost ready to make a PR, I  just have a couple of questions.

In search.cpp, many functions start with a call to getData(), which returns either top_block_data_ or an element of child_block_data_, but I cant see where top_block_data_ is populated to begin with? This is a private field of the Search class, but it is never modified in search.cpp. Where is top_block_data_ set?

In layoutViewer.cpp on line 882 there is a comment "Look for an instance since no shape was found". I am not sure what is meant by this comment, because it seems everything up to this point in the selectAt() function involves searching for selected objects and adding them to a selections vector. What is the purpose of this comment?

**Comment by gadfort** [comment]
@Iyury1 the comment on line 882 looks to be leftover from long ago when select would only pick the first item it encountered.
