### ISSUE TITLE
Account for macro clock network latency in CTS optimization

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#3759]
### Description

Otherwise, you can end up with a lot of skew

### Suggested Solution

@maliberty You had some ideas?

**Comment by maliberty** [comment]
There are two parts here

1) When building a .lib abstract for a block we should record the clock tree delay.  The exact property is to be provided by My unless someone knows it offhand

2) When building the clock tree at the top level the latency that is inside the macro should be taken in to account.

**Comment by maliberty** [comment]
From https://www.eng.biu.ac.il/temanad/files/2017/02/Lecture-8-CTS.pdf
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/761514/d47f8ce6-9b2d-4cc2-8c64-dbd59b67aa45)

This shows the idea though we don't want this command but to automate it through .lib.

**Comment by maliberty** [comment]
For the related .lib attributes:
```
max_clock_tree_path
Used in timing groups under a clock pin. Defines the maximum clock tree path constraint.
min_clock_tree_path
Used in timing groups under a clock pin. Defines the minimum clock tree path constraint.
```

**Comment by maliberty** [comment]
@louiic to write a more detailed spec

**Comment by oharboe** [comment]
@maliberty @tspyrou Is this more detailed spec in place?

**Comment by precisionmoon** [comment]
We plan to enhance insertion delay support as follows:
1) Enhance H-Tree to pull macros with insertion delays ahead of FF leaves
2) Enhance OpenSTA to include insertion delay in report_clock_skew
3) Enhance clock tree viewer to include insertion delays (optional)

1) and 2) are targeted by end of Feb.   If needed 3) can be done in mid March.

Thanks.

Cho

**Comment by precisionmoon** [comment]
Here's some intermediate update on the progress.   Part 3: clock tree viewer enhancement is now complete.  Macros sinks and register sinks are now colored differently and insertion delays are also included in macro cell pin arrival.   Part 1: core HTree enhancement is about 60% complete.   Even though the work of latency adjustment is incomplete, asap7 / mock-array shows promising results.  Here's the current clock tree without the new enhancement.   Red sinks are registers and dark cyan macros.
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/141182150/9bbc4888-0048-4b1b-adf0-f01a6c12ae78)
The clock tree changes as follows with the new enhancement (without -balance_levels option.
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/141182150/1e82012b-eb85-4bef-bf87-d7af8fccaf54)
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


sTNS /   skew | CTS   Pre   repair | CTS   Post   repair | CTS   Final | GR | Final | Final   power
-- | -- | -- | -- | -- | -- | --
No ins   delay   No bal   levels | -48K   54.90 | -13.3K   71.01 | -21.4K   73.56 | 0.0   64.77 | 0.0   70.13 | 3.87   mW
Ins   delay   No bal   levels | -107K   -27.55 | -3.6K   -26.39 | -3.6K   -41.57 | -104.07   -49.97 | 0.0   -51.58 | 3.59   mW



</div>


</body>

</html>
Even in the current form, setup TNS is 6X better after CTS final step and total power is 7% better after DR.
The remaining work involves adding buffers to balance macro cell path latencies and register path latencies. 
This will be done by looking at actual path delays, not logic levels.

The project is on track for end of February delivery.

**Comment by oharboe** [comment]
@precisionmoon Some testing & thoughts:

It would be nice to have the clock insertion point for the macro AND the clock insertion latency within the macro indicated in the CTS viewer. The clock insertion latency within the macro could perhaps be indicated a flip-flop after the macro clock insertion point?

The flip-flops of the current design and the flip-flops of the macros should then all line up with a minimum of skew(assuming we try to optimize for minimum of skew, the optimal skew is more complicated...).

**Comment by precisionmoon** [comment]
@oharboe, yes we can enhance the clock tree viewer to highlight the insertion delay.   For now, we'd like to focus on the core task of improving the clock skew.  We'll revisit clock tree viewer later.  Is this OK?

**Comment by precisionmoon** [comment]
@oharboe, did you enable -insertion_delay option?   This is not enabled by default yet.

**Comment by oharboe** [comment]
@precisionmoon So I get this image below :+1: 

What is this image telling me it telling me?

I tink it is telling me, from looking at the 

- The clock insertion latency for the flip-flops is around 329.534ps, as I can see by looking at one flip-flop
- Looking at an Element, the clock insertion latency is around 442.233ps. However, the clock insertion latency *within* the Element is in addition to this. The Element.lib file is identical with and without the `-insertion_delay` change to cts.tcl, I expected it to be different.


![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/1a238b84-fc2a-4866-b212-f4ded556b25c)

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/827c92a5-c625-4310-8386-c7131a481201)

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/2798822/35e2e323-557e-452d-b1a3-7efa26fb0f37)

**Comment by precisionmoon** [comment]
@oharboe, 

>Looking at an Element, the clock insertion latency is around 442.233ps. However, the clock insertion latency within the >Element is  in addition to this. 

No, the arrival at macro pin of 442.233 ps already includes insertion delay of ~70 ps for the Element.  This is part of my recent GUI change.

  cell ("Element") {
    interface_timing : true;
    pin("clock") {
      direction : input;
      clock : true;
      capacitance : 3.6238;
      timing() {
        timing_sense : positive_unate;
        timing_type : min_clock_tree_path;
	cell_rise(scalar) {
          values("70.88061");
	}
	cell_fall(scalar) {
          values("72.71306");
	}
      }

Now, I'm trying to balance the latencies by inserting buffers at the common point.  This is more efficient than adding buffers along individual latency paths.  Does this make sense?

**Comment by oharboe** [comment]
Yes. As we discussed, future GUI improvement would be a visiual clue/indication of `min_clock_tree_path`.

Looking forward to further improvements.

**Comment by rovinski** [comment]
Maybe one way to represent it is to stretch the cyan rectangle vertically? The top of the rectangle would be when the clock arrives at the port and then the bottom would be after the insertion delay. Like so

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/3936698/00aa929c-4ec9-4c61-be4f-9f1b1c447460)

Although the registers don't do that and I don't think they could scale to that. Another option is to maybe drop a whisker like so?

![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/3936698/c78aeb2e-a65e-428b-95dc-223b7468d233)

**Comment by precisionmoon** [comment]
Delay buffer insertion feature has been checked in today as part of https://github.com/The-OpenROAD-Project/OpenROAD/pull/4607.    Delay buffers are added such that average latencies of all macro cell paths and those of register cell paths can match.   For example, if the difference in macro cell latencies and register cell latencies is 50 ps and each delay buffer delay is 10 ps, we need 5 delay buffers to balance the latencies.  -delay_buffer_derate option has been added to control number of delay buffers.   Default is 1.0, meaning all the intended delay buffers will be added.  0.0 means no delay buffers.
Here are some prelim results on asap7/mock-array.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


sTNS /   skew | CTS   Pre   repair | CTS   Post   repair | CTS   Final | GR | Final | Final   power
-- | -- | -- | -- | -- | -- | --
Base   No   insertion delay | -48K   54.90 | -13.3K   71.01 | -21.4K   73.56 | 0.0   64.77 | 0.0   70.13 | 3.87   mW
Ins   delay   0   delay buffers   -insertion_delay   -delay_buffer_derate   0.0 | -107K   -27.55 | -3.6K   -26.39 | -3.6K   -41.57 | -104.07   -49.97 | 0.0   -51.58 | 3.59   mW
Ins   delay   1   delay buffer   -insertion_delay   -delay_buffer_derate   0.2 | -106K   -20.51 | -3.29K   -21.57 | -3.2K   -36.47 | -40.14   -45.99 | 0.0   -47.81 | 3.61   mW
Ins   delay   2   delay buffers   -insertion_delay   -delay_buffer_derate   0.5 | -107K   -27.67 | -3.7K   -28.08 | -3.7K   -43.55 | -178.66   -52.72 | 0.0   -52.53 | 3.65   mW
Ins   delay   5   delay buffers   -insertion_delay   -delay_buffer_derate   1.0 | -110K   -65.63 | -6.2K   -66.36 | -6.2K   -82.42 | -2338.12   -92.09 | -1382.6   -88.94 | 3.79   mW



</div>


</body>

</html>

Clock tree with 5 delay buffers looks as follows:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/141182150/ad514cd2-1e06-41bc-8e8b-d80e895f7cb4)

Clock tree with 1 delay buffer looks as follows:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/141182150/1caf47a7-898d-4648-9740-961b27df03fe)

This looks similar to the clock tree without any delay buffers because post CTS repair step adds some additional buffers.

Some more work is needed to tune the algorithm to produce the best skew and timing QoR.

**Comment by precisionmoon** [comment]
We enhanced the feature to support handling of macro trees with a single sink.  Latency adjustment now happens for such scenarios also.
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/141182150/cc44944b-1c40-4526-a81f-936dc49896de)
Also, the feature is enabled by default now, so -insertion_delay is no longer needed.  To disable the feature, use "-no_insertion_delay" option.   Since the PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/4678
 has been merged, we're closing this issue.
