### ISSUE TITLE
auto_place_pins multiple layers

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenROAD#40]
Hello,
`auto_place_pins pin_layer` Places pins on a single layer. It should be able to place vertical pins (sides of the die) and horizontal pins (top and bottom of the die) in separate layers.

**Comment by rovinski** [comment]
Hi @kareefardi,

I currently recommend using `io_placer` instead of `auto_place_pins`. Here's an example:
```
io_placer -hor_layer 3 -ver_layer 2`
```
Note that `io_placer` uses cell placement information to guide the I/O pin placement. If placement has not yet been run, the `-random` flag is required, which will distribute the pins evenly over the die boundary.
