### ISSUE TITLE
Add saving of macro placement

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#4068]
### Description

Add support for moving and rotating macros from the GUI, snapping to the grid as well as saving of macro placement.

### Suggested Solution

1. grab and move macro, by default snapping to the grid so that detailed router and other stages do not run into trouble.
2. add a `write_placement foo.tcl` command.

**Comment by rovinski** [comment]
Snap to which grid? A macro can have arbitrary pin sizes and shapes and it would be extremely difficult to ensure that an arbitrary macro is snapped to the routing grid. Also, pins on different layers could want to snap to different tracks so that at least 1 layer isn't aligned.

There's a lot of potential for this feature to cause frustration if the macro doesn't follow standard conventions exactly. If you supply some more details about the expected behavior, then I imagine this request could gain better traction.

**Comment by oharboe** [comment]
@rovinski I am afraid I dont know exactly what the constraints are, I was hoping some expert domain knowledge of this could be built into the GUI

**Comment by rovinski** [comment]
Well, you know how with Microsoft Word or PowerPoint when you move an image around and it snaps to everything except how you want it? That's what I am worried about. 😅

Here's an example of a macro with no good way to snap because of pins off track:
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/3936698/b3fbd1d6-d5d8-4325-8e51-e1d5ad2155e5)

Here's an example of no good way to snap because of pins and tracks misaligned between layers
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/3936698/b9767546-f616-472e-a81e-227d5d9e4c29)

Here's an example of very difficult to determine snapping because of polygon pin shapes
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/3936698/f7b69cce-cb0b-4846-ad42-b0d7dec717d7)

Here's an example of too many potential snapping points because of wide pins
![image](https://github.com/The-OpenROAD-Project/OpenROAD/assets/3936698/8b77d414-9d01-4f25-a148-421c2d5db343)

So I fear that checking for all of these arbitrary conditions would be difficult. Realistically there would have to be a lot of checking to see if a macro could be easily snapped to the routing grid.
Snapping to the placement grid or the manufacturing grid would be much more straightforward.

**Comment by maliberty** [comment]
Based on the discussion in #4069 I'm dropping the GUI editing and suggesting we just add a write_macro_placement  command to mpl2.

**Comment by maliberty** [comment]
I believe the intention would be to save all the macro placements into one file.
