### ISSUE TITLE
GRT: update congestion estimation in GCells when fat vias are necessary

### ISSUE THREAD

**Issue by eder-matheus** [The-OpenROAD-Project/OpenROAD#4786]
In GCells where using fat vias is the only option, the resources should be decreased by 50%. With this, the global router will not assign too many wires to these regions, avoiding the problem of having unsolvable DRCs in the detailed routing stage.

**Comment by rovinski** [comment]
Is this a 50% reduction to the layer or a 50% reduction to layer transitions? It seems overly conservative to reduce the layer by 50%.

**Comment by maliberty** [comment]
There is no via capacity modeling in fastroute so it in in layer resource.  The problem is that with only a fat via you block any adjacent track if wrong way is not allowed whenever you use a via.  We see this as a source of hard to fix problems in a particular PDK.  Once we can support the full set of wrong way rules this may be less needed and can be revisited.  50% is a rough but conservative guess.  It typically only occurs over macros so the general impact is limited.

**Comment by rovinski** [comment]
I see, so this is reduction is intended only for subset of GCells and not all GCells? Makes sense.
