### ISSUE TITLE
Make `[INFO GPL-0075] Routability numCall: 5 inflationIterCnt: 0 bloatIterCnt: 1` more actionable

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenROAD#5201]
### Description

When global place is taking a long time, it is hard for the user to know what it is that is needed to speed it up based upon the info printed.

During architectural exploration, it is oftentimes more important to get an approximate result quickly than to get the best result. The user has to state his intention through modifying ORFS options to e.g. skip routability calls, but connecting the dots from the info below to the ORFS could be easier.

```
[INFO GPL-0075] Routability numCall: 5 inflationIterCnt: 0 bloatIterCnt: 1
```

### Suggested Solution

Change wording of this info to be more actionable. I know there is something that can be adjusted in ORFS to speed things up here, like disable placement w.r.t. routability?

**Comment by gudeh** [comment]
The actionable request for the user point of view was previously attended with an enhanced explanation of how routability mode in gpl works. 

The runtime was fixed with the substitution of RUDY for fastroute to provide routing congestion estimation.

Lastly, the log was changed for better quality in PR https://github.com/The-OpenROAD-Project/OpenROAD/pull/6269
