### ISSUE TITLE
FastRoute routing over obstructions

### ISSUE THREAD

**Issue by ax3ghazy** [The-OpenROAD-Project/OpenROAD#561]
I simplified the test case as far as I could.

[fastroute_through_obs.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/5797936/fastroute_through_obs.tar.gz)

To reproduce, run the script included and view the guides produced for the "la_data_in[9]" net. This misguides TritonRoute causing shorts through obstructed macros. 

![screenshot_20210111_21-25-06](https://user-images.githubusercontent.com/19731159/104228436-87a9c100-5453-11eb-82d8-8699991c3a72.png)

**Comment by juspertor** [comment]
I can confirm this issue. Obstruction macros are not respected and also pdn-rails are ignored. I can supply further test cases if needed. 

![Screenshot_20210113_155033](https://user-images.githubusercontent.com/38461862/104468300-98734780-55b7-11eb-9a75-607af264daed.png)

red marked shapes were added by TritonRoute and causing a short

![Screenshot_20210113_155203](https://user-images.githubusercontent.com/38461862/104468333-9f9a5580-55b7-11eb-9c6d-ebf4f0083cc8.png)

**Comment by eder-matheus** [comment]
@ax3ghazy FastRoute creates _met4_ guides over the _met4_ macro obstructions because there are free tracks between these obstructions. If you zoom the macro obs, you will be able to see it.

I'd suggest you use the "-macro_extension _n_" option. With this, the macro obstacles are extended in _n_ gcells. In my tests, using "-macro_extension 1" was enough to avoid routing over the macro obs.
